functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
 - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
 - Сайт должен иметь мобильную версию.
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
 - Сайт должен быть доступен на различных устройствах.
implicit:
 - Сайт должен иметь нумерацию страниц
 - 
  
  
  

